# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/olaf/CLionProjects/cealr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/olaf/CLionProjects/cealr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/olaf/CLionProjects/cealr/CMakeFiles /Users/olaf/CLionProjects/cealr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/olaf/CLionProjects/cealr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cealr

# Build rule for target.
cealr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cealr
.PHONY : cealr

# fast build rule for target.
cealr/fast:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/build
.PHONY : cealr/fast

src/CurlUtil.o: src/CurlUtil.cpp.o

.PHONY : src/CurlUtil.o

# target to build an object file
src/CurlUtil.cpp.o:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/CurlUtil.cpp.o
.PHONY : src/CurlUtil.cpp.o

src/CurlUtil.i: src/CurlUtil.cpp.i

.PHONY : src/CurlUtil.i

# target to preprocess a source file
src/CurlUtil.cpp.i:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/CurlUtil.cpp.i
.PHONY : src/CurlUtil.cpp.i

src/CurlUtil.s: src/CurlUtil.cpp.s

.PHONY : src/CurlUtil.s

# target to generate assembly for a file
src/CurlUtil.cpp.s:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/CurlUtil.cpp.s
.PHONY : src/CurlUtil.cpp.s

src/Properties.o: src/Properties.cpp.o

.PHONY : src/Properties.o

# target to build an object file
src/Properties.cpp.o:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/Properties.cpp.o
.PHONY : src/Properties.cpp.o

src/Properties.i: src/Properties.cpp.i

.PHONY : src/Properties.i

# target to preprocess a source file
src/Properties.cpp.i:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/Properties.cpp.i
.PHONY : src/Properties.cpp.i

src/Properties.s: src/Properties.cpp.s

.PHONY : src/Properties.s

# target to generate assembly for a file
src/Properties.cpp.s:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/Properties.cpp.s
.PHONY : src/Properties.cpp.s

src/cealr.o: src/cealr.cpp.o

.PHONY : src/cealr.o

# target to build an object file
src/cealr.cpp.o:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/cealr.cpp.o
.PHONY : src/cealr.cpp.o

src/cealr.i: src/cealr.cpp.i

.PHONY : src/cealr.i

# target to preprocess a source file
src/cealr.cpp.i:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/cealr.cpp.i
.PHONY : src/cealr.cpp.i

src/cealr.s: src/cealr.cpp.s

.PHONY : src/cealr.s

# target to generate assembly for a file
src/cealr.cpp.s:
	$(MAKE) -f CMakeFiles/cealr.dir/build.make CMakeFiles/cealr.dir/src/cealr.cpp.s
.PHONY : src/cealr.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cealr"
	@echo "... src/CurlUtil.o"
	@echo "... src/CurlUtil.i"
	@echo "... src/CurlUtil.s"
	@echo "... src/Properties.o"
	@echo "... src/Properties.i"
	@echo "... src/Properties.s"
	@echo "... src/cealr.o"
	@echo "... src/cealr.i"
	@echo "... src/cealr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

